# action.yml

name: Workflow Badge Action
author: srfoster65
description: Create a workflow badge and commit to badges branch
inputs:
  label:
    description: The left text of the badge
    required: true
  label-color:
    description: Hex or named color for the subject
    required: true
    default: 555
  status:
    description: The right text of the badge.
    required: true
  color:
    description: Hex or named color for the status
    required: true
    default: blue
  style:
    description: "Badge style: flat or classic"
    required: true
    default: classic
  icon:
    description: Use icon
    required: false
  icon-width:
    description: Set this if icon is not square
    required: false
    default: 13
  scale:
    description: Set badge scale
    required: true
    default: 1
  path:
    description: Save the badge to path.
    required: false
    # default: main
  branch:
    description: Path to use for committing badges
    required: true
    default: badges
outputs:
  badge:
    description: The badge SVG contents

runs:
  using: composite
  steps:

    # Get current banch name to use it as dest directory
    - name: Extract branch name
      id: extract_branch
      shell: bash
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> "${GITHUB_OUTPUT}"

    - name: Prepare environment
      # This step defines the branch and path to use for committing the badge
      id: prepare_env
      shell: bash
      run: |
        # Output values to be used by other steps
        # path is the full path (incl. filename) of the badge
        echo "path=${BADGE_PATH}" >> "${GITHUB_OUTPUT}"
        # branch is destination branch - defaults of "badges"
        echo "branch=${BRANCH}" >> "${GITHUB_OUTPUT}"
      env:
        BADGE_PATH: ${{ steps.extract_branch.outputs.branch }}/${{ inputs.label }}.svg
        BRANCH: ${{ inputs.branch }}

    - uses: actions/checkout@v4
      # This step will fail if badge commit branch does not exist
      with:
        ref: ${{ steps.prepare_env.outputs.branch }}

    # Create the directory where badges will be saved, if needed
    - name: Create destination directory
      env:
        BADGE_PATH: ${{ steps.prepare_env.outputs.path }}
      shell: bash
      run: mkdir -p "${BADGE_PATH%/*}"

    - name: Generate the badge SVG image
      uses: emibcn/badge-action@v2.0.2
      id: create_badge
      with:
        label: ${{ inputs.label }}
        status: ${{ inputs.status }}
        color: ${{ inputs.color }}
        icon: ${{ inputs.icon }}
        path: ${{ steps.prepare_env.outputs.path }}

    - name: Upload badge as artifact
      uses: actions/upload-artifact@v3
      with:
        name: badge
        path: ${{ steps.prepare_env.outputs.path }}
        if-no-files-found: error

    - name: Commit badge
      continue-on-error: true
      env:
        BADGE: ${{ steps.prepare_env.outputs.path }}
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add "${BADGE}"
        git commit -m "Add/Update badge"

    - name: Push badge commit
      uses: ad-m/github-push-action@master
      if: ${{ success() }}
      with:
        # github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.prepare_env.outputs.branch }}
