# action.yml

name: Workflow Badge Action
author: srfoster65
description: Create a workflow badge and commit to badges branch
inputs:
  label:
    description: The left text of the badge
    required: true
    default: ${{ github.job }}
  label-color:
    description: Hex or named color for the subject
    required: true
    default: grey
  status:
    description: The right text of the badge.
    required: true
  color:
    description: Hex or named color for the status
    required: true
    default: blue
  style:
    description: "Badge style: flat or classic"
    required: true
    default: classic
  icon:
    description: Use icon
    required: false
    default: github
  icon-width:
    description: Set this if icon is not square
    required: false
    default: 13
  scale:
    description: Set badge scale
    required: true
    default: 1
  type:
    description: Either workflow or custon
    required: true
    default: workflow
  badges_branch:
    description: Allow overriding default branch used to store badges
    required: true
    default: badges

runs:
  using: composite
  steps:

    # Get current banch name (for use as dest directory when committing badge)
    - name: Extract working branch name
      id: extract_branch
      shell: bash
      run: echo "working_branch=${GITHUB_REF#refs/heads/}" >> "${GITHUB_OUTPUT}"

    - name: Get Badge Info
      # This step defines the badges branch and full path to use for committing the badge
      id: badge_info
      shell: bash
      run: |
        # Output values to be used by other steps of the workflow
        # path is the full path (incl. filename) of the badge
        echo "badge_path=${BADGE_PATH}" >> "${GITHUB_OUTPUT}"
        # badges_branch is destination branch - default: badges
        echo "badges_branch=${BADGES_BRANCH}" >> "${GITHUB_OUTPUT}"
      env:
        BADGE_PATH: ${{ steps.extract_branch.outputs.working_branch }}/${{ inputs.label }}.svg
        BADGES_BRANCH: ${{ inputs.badges_branch }}

    - name: install python
      id: install_python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 
        cache: 'pip' # caching pip dependencies

    - name: install requirements
      shell: bash
      run: pip install -r requirements.txt

    - name: Generate the badge SVG image
      # Badge svg can accessed as steps.create_badge.outputs.badge
      id: create_badge
      shell: bash
      run: python src/create_badge.py -l ${{ inputs.label }} -s ${{ inputs.status }} -i ${{ inputs.icon }} -c ${{ inputs.colour }} -t ${{ inputs.type }}

    - uses: actions/checkout@v4
      # Checkout the badges_branch
      with:
        ref: ${{ steps.badge_info.outputs.badges_branch }}

    - name: Create destination directory
      # Create a destination directory for the badge.
      env:
        BADGE_PATH: ${{ steps.badge_info.outputs.badge_path }}
      shell: bash
      run: mkdir -p "${BADGE_PATH%/*}"

    - name: write_to_file
      # Save the badge svg to file
      shell: bash
      run: printf '%s\n' '${{ steps.create_badge.outputs.badge }}' > ${{ steps.badge_info.outputs.badge_path }}

    - name: Upload badge as artifact
      uses: actions/upload-artifact@v3
      with:
        name: badge
        path: ${{ steps.badge_info.outputs.badge_path }}
        if-no-files-found: error

    - uses: EndBug/add-and-commit@v9
      # Commit the badge
      with:
        message: "Add/Update badge"
        add: ${{ steps.badge_info.outputs.badge_path }}

    - name: Push badge commit
      # Push the badge to origin on the badges branch
      uses: ad-m/github-push-action@master
      if: ${{ success() }}
      with:
        branch: ${{ steps.badge_info.outputs.badges_branch }}
