name: test echo

on:
  workflow_call:
  
jobs:
  echo:
    name: test echo
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Echo command
      id: echo
      shell: bash
      run: echo "Hello World"

    - name: create badge
      uses: srfoster65/workflow_badge_action@main
      with:
        label: ${{ github.job}}
        status: ${{ steps.echo.outcome }}
