name: 50 percent

on:
  workflow_call:
  
jobs:
  percent_50:
    name: test 50 percent
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4



  create_badge:
    name: create badge
    runs-on: ubuntu-latest
    needs: percent_50
    concurrency:
      group: badge

    steps:
    - name: create badge
      uses: srfoster65/workflow_badge_action@main
      with:
        type: percentage
        label: ${{ github.job}}
        status: 50
