name: 0 percent

on:
  workflow_call:
  
jobs:
  percent_0:
    name: test 0 percent
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

  create_badge:
    name: create badge
    runs-on: ubuntu-latest
    needs: percent_0
    concurrency:
      group: badge

    steps:
    - name: create badge
      uses: srfoster65/workflow_badge_action@main
      with:
        type: percentage
        label: ${{ github.job}}
        status: 0
