name: 0 percent

on:
  workflow_call:
  
jobs:
  percent_0:
    name: percent 0 badge
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: create badge
      uses: srfoster65/workflow_badge_action@main
      with:
        type: percentage
        label: ${{ github.job}}
        status: 0
