name: test

on:
  push:
    branches:
    - '*'
    - '!badges'
  workflow_dispatch:
  
jobs:
  test:
    name: test badge action
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: create badge
      uses: srfoster65/workflow_badge_action@main
      with:
        label: test
        status: passing
        color: green
        # icon: https://raw.githubusercontent.com/badgen/badgen-icons/master/icons/github.svg
        icon: github
