name: test

on:
  push:
    branches:
    - '*'
    - '!badges'
  workflow_dispatch:
  
jobs:
  test:
    name: test badge action
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Dummy step
      id: dummy
      shell: bash
      run: echo "Hello World"

    - name: create badge
      uses: srfoster65/workflow_badge_action@main
      with:
        label: echo
        status: ${{ steps.dummy.outcome }}
