name: workflow fail

on:
  workflow_call:
  
jobs:
  workflow_fail:
    name: failing workflow badge
    runs-on: ubuntu-latest
    concurrency:
      group: badge
      cancel-in-progress: false
    
    steps:
    - uses: actions/checkout@v4

    - name: create badge
      uses: srfoster65/workflow_badge_action@main
      with:
        label: ${{ github.job}}
        status: failure
