name: workflow fail

on:
  workflow_call:
  
jobs:
  workflow_fail:
    name: test workflow fail
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


  create_badge:
    name: create badge
    runs-on: ubuntu-latest
    needs: workflow_fail
    concurrency:
      group: badge
    
    steps:
    - name: create badge
      uses: srfoster65/workflow_badge_action@main
      with:
        label: ${{ github.job}}
        status: failure
