
name: Test workflow badge action

on:
  push:
    branches:
    - '*'
    - '!badges'
  workflow_dispatch:
        
jobs:
  create_badges:
    name: test badges
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: workflow_passing
      uses: ./.github/workflows/workflow_pass.yml
    
    - name: workflow_failing
      uses: ./.github/workflows/workflow_fail.yml

    - name: percentage_50
      uses: ./.github/workflows/percentage_0.yml

    - name: percentage_50
      uses: ./.github/workflows/percentage_50.yml

    - name: percentage_100
      uses: ./.github/workflows/percentage_100.yml
