# Cannot use reusable workflows with local actions
# As action commits to git all badges must be created sequentially

name: Test workflow badge action

on:
  push:
    branches:
    - '*'
    - '!badges'
  workflow_dispatch:

jobs:
  create_badges:
    name: test badges
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: workflow passing badge
      uses: srfoster65/workflow_badge_action@main
      with:
        label: ${{ github.job}}
        status: success

    - name: workflow failing badge
      uses: srfoster65/workflow_badge_action@main
      with:
        label: ${{ github.job}}
        status: failure

    - name: percent 0 badge
      uses: srfoster65/workflow_badge_action@main
      with:
        type: percentage
        label: ${{ github.job}}
        status: 0

    - name: percent 50 badge
      uses: srfoster65/workflow_badge_action@main
      with:
        type: percentage
        label: ${{ github.job}}
        status: 50

    - name: percent 100 badge
      uses: srfoster65/workflow_badge_action@main
      with:
        type: percentage
        label: ${{ github.job}}
        status: 100
  