name: workflow pass

on:
  workflow_call:
  
jobs:
  workflow_pass:
    name: create badge
    runs-on: ubuntu-latest
    concurrency:
      group: badge
      
    steps:
    - uses: actions/checkout@v4
      
    - name: create badge
      uses: srfoster65/workflow_badge_action@main
      with:
        label: ${{ github.job}}
        status: success
