
name: Test workflow badge action

on:
  push:
    branches:
    - '*'
    - '!badges'
  workflow_dispatch:
        
jobs:

  test:
    name: test workflow badge
    uses: ./.github/workflows/echo.yml
